apiVersion: v1
kind: ServiceAccount
metadata:
  name: weathernews-api
  namespace: weather-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weathernews-api
  namespace: weather-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weathernews-api
  namespace: weather-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weathernews-api
subjects:
- kind: ServiceAccount
  name: weathernews-api
  namespace: weather-system